import '@/styles/globals.css'
import { Montserrat } from "next/font/google"
import Head from 'next/head'

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: "--font-mont",
})



export default function App({ Component, pageProps }) {
  <>
    <Head>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
    </Head>
    <main className={`${montserrat.variable} font-mont bg-light w-full min-h-screen`}>
      return <Component {...pageProps} />
    </main>
  </>
}
